#ifndef __BOARD_ID_CONF_GPIOS__
#define __BOARD_ID_CONF_GPIOS__

#define CORE_ALIVE_LED_1 0
#define CORE_ALIVE_LED_2 1
#define CORE_ALIVE_LED_3 2

#define AIR_PRECHARGE_INIT 3
#define AIR_PRECHARGE_DONE 4

#define SCS 5

#define READY_TO_DRIVE_INPUT_BUTTON 6
#define READY_TO_DRIVE_OUT_LED 7
#define READY_TO_DRIVE_OUT_SOUND 8

#define ASSI_LIGHT_BLU 9
#define ASSI_LIGHT_YELLOW 10

#define AS_EMERGENCY_SOUND 11

#endif // !__BOARD_ID_CONF_GPIOS__
