/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "can2.h"
#include <inttypes.h>
#include <math.h> /* uses macros NAN, INFINITY, signbit, no need for -lm */
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

/* unpack754() -- unpack a floating point number from IEEE-754 format */ 
static double unpack754(const uint64_t i, const unsigned bits, const unsigned expbits) {
	if (i == 0) return 0.0;

	const uint64_t expset = ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);
	if ((i & expset) == expset) { /* NaN or +/-Infinity */
		if (i & ((1uLL << (bits - expbits - 1)) - 1uLL)) /* Non zero Mantissa means NaN */
			return NAN;
		return (i & (1uLL << (bits - 1))) ? -INFINITY : INFINITY;
	}

	/* pull the significand */
	const unsigned significandbits = bits - expbits - 1; /* - 1 for sign bit */
	double result = (i & ((1LL << significandbits) - 1)); /* mask */
	result /= (1LL << significandbits);  /* convert back to float */
	result += 1.0f;                        /* add the one back on */

	/* deal with the exponent */
	const unsigned bias = (1 << (expbits - 1)) - 1;
	long long shift = ((i >> significandbits) & ((1LL << expbits) - 1)) - bias;
	while (shift > 0) { result *= 2.0; shift--; }
	while (shift < 0) { result /= 2.0; shift++; }
	
	return ((i >> (bits - 1)) & 1) ? -result : result; /* sign it, and return */
}

static inline float    unpack754_32(uint32_t i) { return unpack754(i, 32, 8); }
static inline double   unpack754_64(uint64_t i) { return unpack754(i, 64, 11); }


/* pack754() -- pack a floating point number into IEEE-754 format */ 
static uint64_t pack754(const double f, const unsigned bits, const unsigned expbits) {
	if (f == 0.0) /* get this special case out of the way */
		return signbit(f) ? (1uLL << (bits - 1)) :  0;
	if (f != f) /* NaN, encoded as Exponent == all-bits-set, Mantissa != 0, Signbit == Do not care */
		return (1uLL << (bits - 1)) - 1uLL;
	if (f == INFINITY) /* +INFINITY encoded as Mantissa == 0, Exponent == all-bits-set */
		return ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);
	if (f == -INFINITY) /* -INFINITY encoded as Mantissa == 0, Exponent == all-bits-set, Signbit == 1 */
		return (1uLL << (bits - 1)) | ((1uLL << expbits) - 1uLL) << (bits - expbits - 1);

	long long sign = 0;
	double fnorm = f;
	/* check sign and begin normalization */
	if (f < 0) { sign = 1; fnorm = -f; }

	/* get the normalized form of f and track the exponent */
	int shift = 0;
	while (fnorm >= 2.0) { fnorm /= 2.0; shift++; }
	while (fnorm < 1.0)  { fnorm *= 2.0; shift--; }
	fnorm = fnorm - 1.0;

	const unsigned significandbits = bits - expbits - 1; // -1 for sign bit

	/* calculate the binary form (non-float) of the significand data */
	const long long significand = fnorm * (( 1LL << significandbits) + 0.5f);

	/* get the biased exponent */
	const long long exp = shift + ((1LL << (expbits - 1)) - 1); // shift + bias

	/* return the final answer */
	return (sign << (bits - 1)) | (exp << (bits - expbits - 1)) | significand;
}

static inline uint32_t   pack754_32(const float  f)   { return   pack754(f, 32, 8); }
static inline uint64_t   pack754_64(const double f)   { return   pack754(f, 64, 11); }


static int pack_can_0x052_Paddle(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* regen: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x052_Paddle.regen)) & 0xff;
	i |= x;
	*data = (i);
	o->can_0x052_Paddle_tx = 1;
	return 1;
}

static int unpack_can_0x052_Paddle(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* regen: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x052_Paddle.regen = x;
	o->can_0x052_Paddle_rx = 1;
	o->can_0x052_Paddle_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x052_regen(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x052_Paddle.regen);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x052_regen(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x052_Paddle.regen = 0;
	if (in > 100)
		return -1;
	o->can_0x052_Paddle.regen = in;
	return 0;
}

int print_can_0x052_Paddle(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "regen = (wire: %.0f)\n", (double)(o->can_0x052_Paddle.regen)));
	return r;
}

static int pack_can_0x053_Driver(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* steering: start-bit 16, length 12, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x053_Driver.steering)) & 0xfff;
	x <<= 16; 
	i |= x;
	/* throttle: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.throttle)) & 0xff;
	i |= x;
	/* brake: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.brake)) & 0xff;
	x <<= 8; 
	i |= x;
	/* no_implausibility: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.no_implausibility)) & 0x1;
	x <<= 28; 
	i |= x;
	/* bre_implausibility: start-bit 29, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.bre_implausibility)) & 0x1;
	x <<= 29; 
	i |= x;
	/* pad_implausibility: start-bit 30, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.pad_implausibility)) & 0x1;
	x <<= 30; 
	i |= x;
	/* pot_implausibility: start-bit 31, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x053_Driver.pot_implausibility)) & 0x1;
	x <<= 31; 
	i |= x;
	*data = (i);
	o->can_0x053_Driver_tx = 1;
	return 4;
}

static int unpack_can_0x053_Driver(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 4)
		return -1;
	/* steering: start-bit 16, length 12, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xfff;
	x = (x & 0x800) ? (x | 0xf000) : x; 
	o->can_0x053_Driver.steering = x;
	/* throttle: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x053_Driver.throttle = x;
	/* brake: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x053_Driver.brake = x;
	/* no_implausibility: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 28) & 0x1;
	o->can_0x053_Driver.no_implausibility = x;
	/* bre_implausibility: start-bit 29, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 29) & 0x1;
	o->can_0x053_Driver.bre_implausibility = x;
	/* pad_implausibility: start-bit 30, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 30) & 0x1;
	o->can_0x053_Driver.pad_implausibility = x;
	/* pot_implausibility: start-bit 31, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 31) & 0x1;
	o->can_0x053_Driver.pot_implausibility = x;
	o->can_0x053_Driver_rx = 1;
	o->can_0x053_Driver_time_stamp_rx = time_stamp;
	return 4;
}

int decode_can_0x053_steering(const can_obj_can2_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x053_Driver.steering);
	if ((rval >= -120) && (rval <= 120)) {
		*out = rval;
		return 0;
	} else {
		*out = (int16_t)0;
		return -1;
	}
}

int encode_can_0x053_steering(can_obj_can2_h_t *o, int16_t in) {
	assert(o);
	o->can_0x053_Driver.steering = 0;
	if (in < -120)
		return -1;
	if (in > 120)
		return -1;
	o->can_0x053_Driver.steering = in;
	return 0;
}

int decode_can_0x053_throttle(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.throttle);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x053_throttle(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.throttle = 0;
	if (in > 100)
		return -1;
	o->can_0x053_Driver.throttle = in;
	return 0;
}

int decode_can_0x053_brake(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.brake);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x053_brake(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.brake = 0;
	if (in > 100)
		return -1;
	o->can_0x053_Driver.brake = in;
	return 0;
}

int decode_can_0x053_no_implausibility(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.no_implausibility);
	*out = rval;
	return 0;
}

int encode_can_0x053_no_implausibility(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.no_implausibility = in;
	return 0;
}

int decode_can_0x053_bre_implausibility(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.bre_implausibility);
	*out = rval;
	return 0;
}

int encode_can_0x053_bre_implausibility(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.bre_implausibility = in;
	return 0;
}

int decode_can_0x053_pad_implausibility(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.pad_implausibility);
	*out = rval;
	return 0;
}

int encode_can_0x053_pad_implausibility(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.pad_implausibility = in;
	return 0;
}

int decode_can_0x053_pot_implausibility(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x053_Driver.pot_implausibility);
	*out = rval;
	return 0;
}

int encode_can_0x053_pot_implausibility(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x053_Driver.pot_implausibility = in;
	return 0;
}

int print_can_0x053_Driver(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "steering = (wire: %.0f)\n", (double)(o->can_0x053_Driver.steering)));
	r = print_helper(r, fprintf(output, "throttle = (wire: %.0f)\n", (double)(o->can_0x053_Driver.throttle)));
	r = print_helper(r, fprintf(output, "brake = (wire: %.0f)\n", (double)(o->can_0x053_Driver.brake)));
	r = print_helper(r, fprintf(output, "no_implausibility = (wire: %.0f)\n", (double)(o->can_0x053_Driver.no_implausibility)));
	r = print_helper(r, fprintf(output, "bre_implausibility = (wire: %.0f)\n", (double)(o->can_0x053_Driver.bre_implausibility)));
	r = print_helper(r, fprintf(output, "pad_implausibility = (wire: %.0f)\n", (double)(o->can_0x053_Driver.pad_implausibility)));
	r = print_helper(r, fprintf(output, "pot_implausibility = (wire: %.0f)\n", (double)(o->can_0x053_Driver.pot_implausibility)));
	return r;
}

static int pack_can_0x054_BmsLv1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* volt1: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x054_BmsLv1.volt1)) & 0xffff;
	i |= x;
	/* volt2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x054_BmsLv1.volt2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* volt3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x054_BmsLv1.volt3)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* volt4: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x054_BmsLv1.volt4)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x054_BmsLv1_tx = 1;
	return 8;
}

static int unpack_can_0x054_BmsLv1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* volt1: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x054_BmsLv1.volt1 = x;
	/* volt2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x054_BmsLv1.volt2 = x;
	/* volt3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x054_BmsLv1.volt3 = x;
	/* volt4: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x054_BmsLv1.volt4 = x;
	o->can_0x054_BmsLv1_rx = 1;
	o->can_0x054_BmsLv1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x054_volt1(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x054_BmsLv1.volt1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x054_volt1(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x054_BmsLv1.volt1 = in;
	return 0;
}

int decode_can_0x054_volt2(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x054_BmsLv1.volt2);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x054_volt2(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x054_BmsLv1.volt2 = in;
	return 0;
}

int decode_can_0x054_volt3(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x054_BmsLv1.volt3);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x054_volt3(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x054_BmsLv1.volt3 = in;
	return 0;
}

int decode_can_0x054_volt4(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x054_BmsLv1.volt4);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x054_volt4(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x054_BmsLv1.volt4 = in;
	return 0;
}

int print_can_0x054_BmsLv1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "volt1 = (wire: %.0f)\n", (double)(o->can_0x054_BmsLv1.volt1)));
	r = print_helper(r, fprintf(output, "volt2 = (wire: %.0f)\n", (double)(o->can_0x054_BmsLv1.volt2)));
	r = print_helper(r, fprintf(output, "volt3 = (wire: %.0f)\n", (double)(o->can_0x054_BmsLv1.volt3)));
	r = print_helper(r, fprintf(output, "volt4 = (wire: %.0f)\n", (double)(o->can_0x054_BmsLv1.volt4)));
	return r;
}

static int pack_can_0x055_BmsLv2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* volt5: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x055_BmsLv2.volt5)) & 0xffff;
	i |= x;
	/* volt6: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x055_BmsLv2.volt6)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* temp1: start-bit 32, length 16, endianess intel, scaling -0.002248, offset 76 */
	x = ((uint16_t)(o->can_0x055_BmsLv2.temp1)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* temp2: start-bit 48, length 16, endianess intel, scaling -0.002248, offset 76 */
	x = ((uint16_t)(o->can_0x055_BmsLv2.temp2)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x055_BmsLv2_tx = 1;
	return 8;
}

static int unpack_can_0x055_BmsLv2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* volt5: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x055_BmsLv2.volt5 = x;
	/* volt6: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x055_BmsLv2.volt6 = x;
	/* temp1: start-bit 32, length 16, endianess intel, scaling -0.002248, offset 76 */
	x = (i >> 32) & 0xffff;
	o->can_0x055_BmsLv2.temp1 = x;
	/* temp2: start-bit 48, length 16, endianess intel, scaling -0.002248, offset 76 */
	x = (i >> 48) & 0xffff;
	o->can_0x055_BmsLv2.temp2 = x;
	o->can_0x055_BmsLv2_rx = 1;
	o->can_0x055_BmsLv2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x055_volt5(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsLv2.volt5);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x055_volt5(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x055_BmsLv2.volt5 = in;
	return 0;
}

int decode_can_0x055_volt6(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsLv2.volt6);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x055_volt6(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x055_BmsLv2.volt6 = in;
	return 0;
}

int decode_can_0x055_temp1(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsLv2.temp1);
	rval *= -0.002248;
	rval += 76;
	*out = rval;
	return 0;
}

int encode_can_0x055_temp1(can_obj_can2_h_t *o, double in) {
	assert(o);
	in += -76;
	in *= -444.84;
	o->can_0x055_BmsLv2.temp1 = in;
	return 0;
}

int decode_can_0x055_temp2(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x055_BmsLv2.temp2);
	rval *= -0.002248;
	rval += 76;
	*out = rval;
	return 0;
}

int encode_can_0x055_temp2(can_obj_can2_h_t *o, double in) {
	assert(o);
	in += -76;
	in *= -444.84;
	o->can_0x055_BmsLv2.temp2 = in;
	return 0;
}

int print_can_0x055_BmsLv2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "volt5 = (wire: %.0f)\n", (double)(o->can_0x055_BmsLv2.volt5)));
	r = print_helper(r, fprintf(output, "volt6 = (wire: %.0f)\n", (double)(o->can_0x055_BmsLv2.volt6)));
	r = print_helper(r, fprintf(output, "temp1 = (wire: %.0f)\n", (double)(o->can_0x055_BmsLv2.temp1)));
	r = print_helper(r, fprintf(output, "temp2 = (wire: %.0f)\n", (double)(o->can_0x055_BmsLv2.temp2)));
	return r;
}

static int pack_can_0x057_BmsHv1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* max_volt: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsHv1.max_volt)) & 0xffff;
	i |= x;
	/* min_volt: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsHv1.min_volt)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* avg_volt: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x057_BmsHv1.avg_volt)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* soc: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x057_BmsHv1.soc)) & 0xff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x057_BmsHv1_tx = 1;
	return 7;
}

static int unpack_can_0x057_BmsHv1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 7)
		return -1;
	/* max_volt: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x057_BmsHv1.max_volt = x;
	/* min_volt: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x057_BmsHv1.min_volt = x;
	/* avg_volt: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x057_BmsHv1.avg_volt = x;
	/* soc: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x057_BmsHv1.soc = x;
	o->can_0x057_BmsHv1_rx = 1;
	o->can_0x057_BmsHv1_time_stamp_rx = time_stamp;
	return 7;
}

int decode_can_0x057_max_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsHv1.max_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_max_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsHv1.max_volt = in;
	return 0;
}

int decode_can_0x057_min_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsHv1.min_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_min_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsHv1.min_volt = in;
	return 0;
}

int decode_can_0x057_avg_volt(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x057_BmsHv1.avg_volt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x057_avg_volt(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x057_BmsHv1.avg_volt = in;
	return 0;
}

int decode_can_0x057_soc(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x057_BmsHv1.soc);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x057_soc(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x057_BmsHv1.soc = 0;
	if (in > 100)
		return -1;
	o->can_0x057_BmsHv1.soc = in;
	return 0;
}

int print_can_0x057_BmsHv1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x057_BmsHv1.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x057_BmsHv1.min_volt)));
	r = print_helper(r, fprintf(output, "avg_volt = (wire: %.0f)\n", (double)(o->can_0x057_BmsHv1.avg_volt)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x057_BmsHv1.soc)));
	return r;
}

static int pack_can_0x058_BmsHv2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* max_temp: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsHv2.max_temp)) & 0xffff;
	i |= x;
	/* min_temp: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsHv2.min_temp)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* avg_temp: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x058_BmsHv2.avg_temp)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* fan_speed: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x058_BmsHv2.fan_speed)) & 0xff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x058_BmsHv2_tx = 1;
	return 7;
}

static int unpack_can_0x058_BmsHv2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 7)
		return -1;
	/* max_temp: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x058_BmsHv2.max_temp = x;
	/* min_temp: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x058_BmsHv2.min_temp = x;
	/* avg_temp: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x058_BmsHv2.avg_temp = x;
	/* fan_speed: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x058_BmsHv2.fan_speed = x;
	o->can_0x058_BmsHv2_rx = 1;
	o->can_0x058_BmsHv2_time_stamp_rx = time_stamp;
	return 7;
}

int decode_can_0x058_max_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x058_BmsHv2.max_temp);
	*out = rval;
	return 0;
}

int encode_can_0x058_max_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x058_BmsHv2.max_temp = in;
	return 0;
}

int decode_can_0x058_min_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x058_BmsHv2.min_temp);
	*out = rval;
	return 0;
}

int encode_can_0x058_min_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x058_BmsHv2.min_temp = in;
	return 0;
}

int decode_can_0x058_avg_temp(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x058_BmsHv2.avg_temp);
	*out = rval;
	return 0;
}

int encode_can_0x058_avg_temp(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x058_BmsHv2.avg_temp = in;
	return 0;
}

int decode_can_0x058_fan_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x058_BmsHv2.fan_speed);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x058_fan_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x058_BmsHv2.fan_speed = 0;
	if (in > 100)
		return -1;
	o->can_0x058_BmsHv2.fan_speed = in;
	return 0;
}

int print_can_0x058_BmsHv2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_temp = (wire: %.0f)\n", (double)(o->can_0x058_BmsHv2.max_temp)));
	r = print_helper(r, fprintf(output, "min_temp = (wire: %.0f)\n", (double)(o->can_0x058_BmsHv2.min_temp)));
	r = print_helper(r, fprintf(output, "avg_temp = (wire: %.0f)\n", (double)(o->can_0x058_BmsHv2.avg_temp)));
	r = print_helper(r, fprintf(output, "fan_speed = (wire: %.0f)\n", (double)(o->can_0x058_BmsHv2.fan_speed)));
	return r;
}

static int pack_can_0x060_Imu1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* acc_x: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x060_Imu1.acc_x) & 0xffffffff;
	i |= x;
	/* acc_y: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x060_Imu1.acc_y) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x060_Imu1_tx = 1;
	return 8;
}

static int unpack_can_0x060_Imu1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* acc_x: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x060_Imu1.acc_x = unpack754_32(x);
	/* acc_y: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x060_Imu1.acc_y = unpack754_32(x);
	o->can_0x060_Imu1_rx = 1;
	o->can_0x060_Imu1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x060_acc_x(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x060_Imu1.acc_x);
	*out = rval;
	return 0;
}

int encode_can_0x060_acc_x(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x060_Imu1.acc_x = in;
	return 0;
}

int decode_can_0x060_acc_y(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x060_Imu1.acc_y);
	*out = rval;
	return 0;
}

int encode_can_0x060_acc_y(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x060_Imu1.acc_y = in;
	return 0;
}

int print_can_0x060_Imu1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "acc_x = (wire: %g)\n", (double)(o->can_0x060_Imu1.acc_x)));
	r = print_helper(r, fprintf(output, "acc_y = (wire: %g)\n", (double)(o->can_0x060_Imu1.acc_y)));
	return r;
}

static int pack_can_0x061_Imu2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* acc_z: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x061_Imu2.acc_z) & 0xffffffff;
	i |= x;
	/* omega_x: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x061_Imu2.omega_x) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x061_Imu2_tx = 1;
	return 8;
}

static int unpack_can_0x061_Imu2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* acc_z: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x061_Imu2.acc_z = unpack754_32(x);
	/* omega_x: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x061_Imu2.omega_x = unpack754_32(x);
	o->can_0x061_Imu2_rx = 1;
	o->can_0x061_Imu2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x061_acc_z(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x061_Imu2.acc_z);
	*out = rval;
	return 0;
}

int encode_can_0x061_acc_z(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x061_Imu2.acc_z = in;
	return 0;
}

int decode_can_0x061_omega_x(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x061_Imu2.omega_x);
	*out = rval;
	return 0;
}

int encode_can_0x061_omega_x(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x061_Imu2.omega_x = in;
	return 0;
}

int print_can_0x061_Imu2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "acc_z = (wire: %g)\n", (double)(o->can_0x061_Imu2.acc_z)));
	r = print_helper(r, fprintf(output, "omega_x = (wire: %g)\n", (double)(o->can_0x061_Imu2.omega_x)));
	return r;
}

static int pack_can_0x062_Imu3(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* omega_y: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x062_Imu3.omega_y) & 0xffffffff;
	i |= x;
	/* omega_z: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = pack754_32(o->can_0x062_Imu3.omega_z) & 0xffffffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x062_Imu3_tx = 1;
	return 8;
}

static int unpack_can_0x062_Imu3(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* omega_y: start-bit 0, length 32, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffff;
	o->can_0x062_Imu3.omega_y = unpack754_32(x);
	/* omega_z: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->can_0x062_Imu3.omega_z = unpack754_32(x);
	o->can_0x062_Imu3_rx = 1;
	o->can_0x062_Imu3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x062_omega_y(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x062_Imu3.omega_y);
	*out = rval;
	return 0;
}

int encode_can_0x062_omega_y(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x062_Imu3.omega_y = in;
	return 0;
}

int decode_can_0x062_omega_z(const can_obj_can2_h_t *o, float *out) {
	assert(o);
	assert(out);
	float rval = (float)(o->can_0x062_Imu3.omega_z);
	*out = rval;
	return 0;
}

int encode_can_0x062_omega_z(can_obj_can2_h_t *o, float in) {
	assert(o);
	o->can_0x062_Imu3.omega_z = in;
	return 0;
}

int print_can_0x062_Imu3(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "omega_y = (wire: %g)\n", (double)(o->can_0x062_Imu3.omega_y)));
	r = print_helper(r, fprintf(output, "omega_z = (wire: %g)\n", (double)(o->can_0x062_Imu3.omega_z)));
	return r;
}

static int pack_can_0x063_IMUCalib(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* start_imu_calibration: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x063_IMUCalib.start_imu_calibration)) & 0x1;
	i |= x;
	*data = (i);
	o->can_0x063_IMUCalib_tx = 1;
	return 1;
}

static int unpack_can_0x063_IMUCalib(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* start_imu_calibration: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x063_IMUCalib.start_imu_calibration = x;
	o->can_0x063_IMUCalib_rx = 1;
	o->can_0x063_IMUCalib_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x063_start_imu_calibration(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x063_IMUCalib.start_imu_calibration);
	*out = rval;
	return 0;
}

int encode_can_0x063_start_imu_calibration(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x063_IMUCalib.start_imu_calibration = in;
	return 0;
}

int print_can_0x063_IMUCalib(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "start_imu_calibration = (wire: %.0f)\n", (double)(o->can_0x063_IMUCalib.start_imu_calibration)));
	return r;
}

static int pack_can_0x064_Map(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* power: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x064_Map.power)) & 0xf;
	i |= x;
	/* regen: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x064_Map.regen)) & 0xf;
	x <<= 4; 
	i |= x;
	/* torque_rep: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x064_Map.torque_rep)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x064_Map_tx = 1;
	return 2;
}

static int unpack_can_0x064_Map(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* power: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->can_0x064_Map.power = x;
	/* regen: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->can_0x064_Map.regen = x;
	/* torque_rep: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->can_0x064_Map.torque_rep = x;
	o->can_0x064_Map_rx = 1;
	o->can_0x064_Map_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x064_power(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x064_Map.power);
	if ((rval >= 1) && (rval <= 12)) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x064_power(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x064_Map.power = 0;
	if (in < 1)
		return -1;
	if (in > 12)
		return -1;
	o->can_0x064_Map.power = in;
	return 0;
}

int decode_can_0x064_regen(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x064_Map.regen);
	if ((rval >= 1) && (rval <= 12)) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x064_regen(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x064_Map.regen = 0;
	if (in < 1)
		return -1;
	if (in > 12)
		return -1;
	o->can_0x064_Map.regen = in;
	return 0;
}

int decode_can_0x064_torque_rep(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x064_Map.torque_rep);
	if (rval <= 12) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x064_torque_rep(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x064_Map.torque_rep = 0;
	if (in > 12)
		return -1;
	o->can_0x064_Map.torque_rep = in;
	return 0;
}

int print_can_0x064_Map(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "power = (wire: %.0f)\n", (double)(o->can_0x064_Map.power)));
	r = print_helper(r, fprintf(output, "regen = (wire: %.0f)\n", (double)(o->can_0x064_Map.regen)));
	r = print_helper(r, fprintf(output, "torque_rep = (wire: %.0f)\n", (double)(o->can_0x064_Map.torque_rep)));
	return r;
}

static int pack_can_0x065_CarStatus(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* speed: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.speed)) & 0xff;
	x <<= 8; 
	i |= x;
	/* HV: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.HV)) & 0x1;
	i |= x;
	/* R2D: start-bit 1, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.R2D)) & 0x1;
	x <<= 1; 
	i |= x;
	/* RF: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.RF)) & 0x1;
	x <<= 2; 
	i |= x;
	/* AIR1: start-bit 3, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.AIR1)) & 0x1;
	x <<= 3; 
	i |= x;
	/* AIR2: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.AIR2)) & 0x1;
	x <<= 4; 
	i |= x;
	/* precharge: start-bit 5, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x065_CarStatus.precharge)) & 0x1;
	x <<= 5; 
	i |= x;
	*data = (i);
	o->can_0x065_CarStatus_tx = 1;
	return 2;
}

static int unpack_can_0x065_CarStatus(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* speed: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x065_CarStatus.speed = x;
	/* HV: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x065_CarStatus.HV = x;
	/* R2D: start-bit 1, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 1) & 0x1;
	o->can_0x065_CarStatus.R2D = x;
	/* RF: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 2) & 0x1;
	o->can_0x065_CarStatus.RF = x;
	/* AIR1: start-bit 3, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 3) & 0x1;
	o->can_0x065_CarStatus.AIR1 = x;
	/* AIR2: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->can_0x065_CarStatus.AIR2 = x;
	/* precharge: start-bit 5, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 5) & 0x1;
	o->can_0x065_CarStatus.precharge = x;
	o->can_0x065_CarStatus_rx = 1;
	o->can_0x065_CarStatus_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x065_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.speed);
	*out = rval;
	return 0;
}

int encode_can_0x065_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.speed = in;
	return 0;
}

int decode_can_0x065_HV(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.HV);
	*out = rval;
	return 0;
}

int encode_can_0x065_HV(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.HV = in;
	return 0;
}

int decode_can_0x065_R2D(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.R2D);
	*out = rval;
	return 0;
}

int encode_can_0x065_R2D(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.R2D = in;
	return 0;
}

int decode_can_0x065_RF(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.RF);
	*out = rval;
	return 0;
}

int encode_can_0x065_RF(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.RF = in;
	return 0;
}

int decode_can_0x065_AIR1(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.AIR1);
	*out = rval;
	return 0;
}

int encode_can_0x065_AIR1(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.AIR1 = in;
	return 0;
}

int decode_can_0x065_AIR2(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.AIR2);
	*out = rval;
	return 0;
}

int encode_can_0x065_AIR2(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.AIR2 = in;
	return 0;
}

int decode_can_0x065_precharge(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x065_CarStatus.precharge);
	*out = rval;
	return 0;
}

int encode_can_0x065_precharge(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x065_CarStatus.precharge = in;
	return 0;
}

int print_can_0x065_CarStatus(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "speed = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.speed)));
	r = print_helper(r, fprintf(output, "HV = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.HV)));
	r = print_helper(r, fprintf(output, "R2D = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.R2D)));
	r = print_helper(r, fprintf(output, "RF = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.RF)));
	r = print_helper(r, fprintf(output, "AIR1 = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.AIR1)));
	r = print_helper(r, fprintf(output, "AIR2 = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.AIR2)));
	r = print_helper(r, fprintf(output, "precharge = (wire: %.0f)\n", (double)(o->can_0x065_CarStatus.precharge)));
	return r;
}

static int pack_can_0x066_CarSettings(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* max_regen_current: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.max_regen_current)) & 0xff;
	i |= x;
	/* pwr_limit: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.pwr_limit)) & 0xff;
	x <<= 8; 
	i |= x;
	/* speed_lim: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.speed_lim)) & 0xff;
	x <<= 16; 
	i |= x;
	/* max_pos_trq: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.max_pos_trq)) & 0xff;
	x <<= 24; 
	i |= x;
	/* max_neg_trq: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.max_neg_trq)) & 0xff;
	x <<= 32; 
	i |= x;
	/* front_motor_repartition: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.front_motor_repartition)) & 0xff;
	x <<= 40; 
	i |= x;
	/* rear_motor_repartition: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.rear_motor_repartition)) & 0xff;
	x <<= 48; 
	i |= x;
	/* torque_vectoring: start-bit 56, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x066_CarSettings.torque_vectoring)) & 0x1;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x066_CarSettings_tx = 1;
	return 8;
}

static int unpack_can_0x066_CarSettings(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* max_regen_current: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x066_CarSettings.max_regen_current = x;
	/* pwr_limit: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x066_CarSettings.pwr_limit = x;
	/* speed_lim: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x066_CarSettings.speed_lim = x;
	/* max_pos_trq: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x066_CarSettings.max_pos_trq = x;
	/* max_neg_trq: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x066_CarSettings.max_neg_trq = x;
	/* front_motor_repartition: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x066_CarSettings.front_motor_repartition = x;
	/* rear_motor_repartition: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x066_CarSettings.rear_motor_repartition = x;
	/* torque_vectoring: start-bit 56, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0x1;
	o->can_0x066_CarSettings.torque_vectoring = x;
	o->can_0x066_CarSettings_rx = 1;
	o->can_0x066_CarSettings_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x066_max_regen_current(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.max_regen_current);
	if (rval <= 150) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x066_max_regen_current(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.max_regen_current = 0;
	if (in > 150)
		return -1;
	o->can_0x066_CarSettings.max_regen_current = in;
	return 0;
}

int decode_can_0x066_pwr_limit(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.pwr_limit);
	if (rval <= 80) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x066_pwr_limit(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.pwr_limit = 0;
	if (in > 80)
		return -1;
	o->can_0x066_CarSettings.pwr_limit = in;
	return 0;
}

int decode_can_0x066_speed_lim(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.speed_lim);
	*out = rval;
	return 0;
}

int encode_can_0x066_speed_lim(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.speed_lim = in;
	return 0;
}

int decode_can_0x066_max_pos_trq(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.max_pos_trq);
	*out = rval;
	return 0;
}

int encode_can_0x066_max_pos_trq(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.max_pos_trq = in;
	return 0;
}

int decode_can_0x066_max_neg_trq(const can_obj_can2_h_t *o, int8_t *out) {
	assert(o);
	assert(out);
	int8_t rval = (int8_t)(o->can_0x066_CarSettings.max_neg_trq);
	*out = rval;
	return 0;
}

int encode_can_0x066_max_neg_trq(can_obj_can2_h_t *o, int8_t in) {
	assert(o);
	o->can_0x066_CarSettings.max_neg_trq = in;
	return 0;
}

int decode_can_0x066_front_motor_repartition(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.front_motor_repartition);
	*out = rval;
	return 0;
}

int encode_can_0x066_front_motor_repartition(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.front_motor_repartition = in;
	return 0;
}

int decode_can_0x066_rear_motor_repartition(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.rear_motor_repartition);
	*out = rval;
	return 0;
}

int encode_can_0x066_rear_motor_repartition(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.rear_motor_repartition = in;
	return 0;
}

int decode_can_0x066_torque_vectoring(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x066_CarSettings.torque_vectoring);
	*out = rval;
	return 0;
}

int encode_can_0x066_torque_vectoring(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x066_CarSettings.torque_vectoring = in;
	return 0;
}

int print_can_0x066_CarSettings(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_regen_current = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.max_regen_current)));
	r = print_helper(r, fprintf(output, "pwr_limit = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.pwr_limit)));
	r = print_helper(r, fprintf(output, "speed_lim = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.speed_lim)));
	r = print_helper(r, fprintf(output, "max_pos_trq = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.max_pos_trq)));
	r = print_helper(r, fprintf(output, "max_neg_trq = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.max_neg_trq)));
	r = print_helper(r, fprintf(output, "front_motor_repartition = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.front_motor_repartition)));
	r = print_helper(r, fprintf(output, "rear_motor_repartition = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.rear_motor_repartition)));
	r = print_helper(r, fprintf(output, "torque_vectoring = (wire: %.0f)\n", (double)(o->can_0x066_CarSettings.torque_vectoring)));
	return r;
}

static int pack_can_0x070_LapStart(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* start: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x070_LapStart.start)) & 0xff;
	i |= x;
	*data = (i);
	o->can_0x070_LapStart_tx = 1;
	return 1;
}

static int unpack_can_0x070_LapStart(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* start: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x070_LapStart.start = x;
	o->can_0x070_LapStart_rx = 1;
	o->can_0x070_LapStart_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x070_start(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x070_LapStart.start);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x070_start(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x070_LapStart.start = 0;
	if (in > 1)
		return -1;
	o->can_0x070_LapStart.start = in;
	return 0;
}

int print_can_0x070_LapStart(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "start = (wire: %.0f)\n", (double)(o->can_0x070_LapStart.start)));
	return r;
}

static int pack_can_0x100_Temp1(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* temp_motor_post_L: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.temp_motor_post_L)) & 0xffff;
	i |= x;
	/* temp_motor_pre_L: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.temp_motor_pre_L)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* temp_motor_pre_R: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.temp_motor_pre_R)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* temp_coldplate_pre_R: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x100_Temp1.temp_coldplate_pre_R)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x100_Temp1_tx = 1;
	return 8;
}

static int unpack_can_0x100_Temp1(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* temp_motor_post_L: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x100_Temp1.temp_motor_post_L = x;
	/* temp_motor_pre_L: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x100_Temp1.temp_motor_pre_L = x;
	/* temp_motor_pre_R: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x100_Temp1.temp_motor_pre_R = x;
	/* temp_coldplate_pre_R: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x100_Temp1.temp_coldplate_pre_R = x;
	o->can_0x100_Temp1_rx = 1;
	o->can_0x100_Temp1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x100_temp_motor_post_L(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.temp_motor_post_L);
	*out = rval;
	return 0;
}

int encode_can_0x100_temp_motor_post_L(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.temp_motor_post_L = in;
	return 0;
}

int decode_can_0x100_temp_motor_pre_L(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.temp_motor_pre_L);
	*out = rval;
	return 0;
}

int encode_can_0x100_temp_motor_pre_L(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.temp_motor_pre_L = in;
	return 0;
}

int decode_can_0x100_temp_motor_pre_R(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.temp_motor_pre_R);
	*out = rval;
	return 0;
}

int encode_can_0x100_temp_motor_pre_R(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.temp_motor_pre_R = in;
	return 0;
}

int decode_can_0x100_temp_coldplate_pre_R(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x100_Temp1.temp_coldplate_pre_R);
	*out = rval;
	return 0;
}

int encode_can_0x100_temp_coldplate_pre_R(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x100_Temp1.temp_coldplate_pre_R = in;
	return 0;
}

int print_can_0x100_Temp1(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "temp_motor_post_L = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.temp_motor_post_L)));
	r = print_helper(r, fprintf(output, "temp_motor_pre_L = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.temp_motor_pre_L)));
	r = print_helper(r, fprintf(output, "temp_motor_pre_R = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.temp_motor_pre_R)));
	r = print_helper(r, fprintf(output, "temp_coldplate_pre_R = (wire: %.0f)\n", (double)(o->can_0x100_Temp1.temp_coldplate_pre_R)));
	return r;
}

static int pack_can_0x101_Temp2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* temp_cold_pre_L: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.temp_cold_pre_L)) & 0xffff;
	i |= x;
	/* temp_cold_post_R: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.temp_cold_post_R)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* temp_cold_post_L: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.temp_cold_post_L)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* temp_mot_post_R: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x101_Temp2.temp_mot_post_R)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x101_Temp2_tx = 1;
	return 8;
}

static int unpack_can_0x101_Temp2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* temp_cold_pre_L: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x101_Temp2.temp_cold_pre_L = x;
	/* temp_cold_post_R: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x101_Temp2.temp_cold_post_R = x;
	/* temp_cold_post_L: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x101_Temp2.temp_cold_post_L = x;
	/* temp_mot_post_R: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x101_Temp2.temp_mot_post_R = x;
	o->can_0x101_Temp2_rx = 1;
	o->can_0x101_Temp2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x101_temp_cold_pre_L(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.temp_cold_pre_L);
	*out = rval;
	return 0;
}

int encode_can_0x101_temp_cold_pre_L(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.temp_cold_pre_L = in;
	return 0;
}

int decode_can_0x101_temp_cold_post_R(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.temp_cold_post_R);
	*out = rval;
	return 0;
}

int encode_can_0x101_temp_cold_post_R(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.temp_cold_post_R = in;
	return 0;
}

int decode_can_0x101_temp_cold_post_L(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.temp_cold_post_L);
	*out = rval;
	return 0;
}

int encode_can_0x101_temp_cold_post_L(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.temp_cold_post_L = in;
	return 0;
}

int decode_can_0x101_temp_mot_post_R(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x101_Temp2.temp_mot_post_R);
	*out = rval;
	return 0;
}

int encode_can_0x101_temp_mot_post_R(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x101_Temp2.temp_mot_post_R = in;
	return 0;
}

int print_can_0x101_Temp2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "temp_cold_pre_L = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.temp_cold_pre_L)));
	r = print_helper(r, fprintf(output, "temp_cold_post_R = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.temp_cold_post_R)));
	r = print_helper(r, fprintf(output, "temp_cold_post_L = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.temp_cold_post_L)));
	r = print_helper(r, fprintf(output, "temp_mot_post_R = (wire: %.0f)\n", (double)(o->can_0x101_Temp2.temp_mot_post_R)));
	return r;
}

static int pack_can_0x102_SuspRear(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* susp_rr: start-bit 0, length 12, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x102_SuspRear.susp_rr)) & 0xfff;
	i |= x;
	/* susp_rl: start-bit 12, length 12, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x102_SuspRear.susp_rl)) & 0xfff;
	x <<= 12; 
	i |= x;
	*data = (i);
	o->can_0x102_SuspRear_tx = 1;
	return 3;
}

static int unpack_can_0x102_SuspRear(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 3)
		return -1;
	/* susp_rr: start-bit 0, length 12, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xfff;
	o->can_0x102_SuspRear.susp_rr = x;
	/* susp_rl: start-bit 12, length 12, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 12) & 0xfff;
	o->can_0x102_SuspRear.susp_rl = x;
	o->can_0x102_SuspRear_rx = 1;
	o->can_0x102_SuspRear_time_stamp_rx = time_stamp;
	return 3;
}

int decode_can_0x102_susp_rr(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x102_SuspRear.susp_rr);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x102_susp_rr(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x102_SuspRear.susp_rr = in;
	return 0;
}

int decode_can_0x102_susp_rl(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x102_SuspRear.susp_rl);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x102_susp_rl(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x102_SuspRear.susp_rl = in;
	return 0;
}

int print_can_0x102_SuspRear(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "susp_rr = (wire: %.0f)\n", (double)(o->can_0x102_SuspRear.susp_rr)));
	r = print_helper(r, fprintf(output, "susp_rl = (wire: %.0f)\n", (double)(o->can_0x102_SuspRear.susp_rl)));
	return r;
}

static int pack_can_0x103_RESERVED2(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	UNUSED(o);
	UNUSED(data);
	o->can_0x103_RESERVED2_tx = 1;
	return 0;
}

static int unpack_can_0x103_RESERVED2(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	UNUSED(o);
	UNUSED(data);
	UNUSED(dlc);
	o->can_0x103_RESERVED2_rx = 1;
	o->can_0x103_RESERVED2_time_stamp_rx = time_stamp;
	return 0;
}

int print_can_0x103_RESERVED2(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	UNUSED(o);
	UNUSED(output);
	return 0;
}

static int pack_can_0x104_SuspFront(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* susp_fr: start-bit 0, length 12, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x104_SuspFront.susp_fr)) & 0xfff;
	i |= x;
	/* susp_fl: start-bit 12, length 12, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x104_SuspFront.susp_fl)) & 0xfff;
	x <<= 12; 
	i |= x;
	*data = (i);
	o->can_0x104_SuspFront_tx = 1;
	return 3;
}

static int unpack_can_0x104_SuspFront(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 3)
		return -1;
	/* susp_fr: start-bit 0, length 12, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xfff;
	o->can_0x104_SuspFront.susp_fr = x;
	/* susp_fl: start-bit 12, length 12, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 12) & 0xfff;
	o->can_0x104_SuspFront.susp_fl = x;
	o->can_0x104_SuspFront_rx = 1;
	o->can_0x104_SuspFront_time_stamp_rx = time_stamp;
	return 3;
}

int decode_can_0x104_susp_fr(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x104_SuspFront.susp_fr);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x104_susp_fr(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x104_SuspFront.susp_fr = in;
	return 0;
}

int decode_can_0x104_susp_fl(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x104_SuspFront.susp_fl);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x104_susp_fl(can_obj_can2_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x104_SuspFront.susp_fl = in;
	return 0;
}

int print_can_0x104_SuspFront(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "susp_fr = (wire: %.0f)\n", (double)(o->can_0x104_SuspFront.susp_fr)));
	r = print_helper(r, fprintf(output, "susp_fl = (wire: %.0f)\n", (double)(o->can_0x104_SuspFront.susp_fl)));
	return r;
}

static int pack_can_0x105_TempFrontR(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* temp_mot_pot_FR: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x105_TempFrontR.temp_mot_pot_FR)) & 0x3ff;
	i |= x;
	/* temp_mot_pre_FR: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x105_TempFrontR.temp_mot_pre_FR)) & 0x3ff;
	x <<= 10; 
	i |= x;
	*data = (i);
	o->can_0x105_TempFrontR_tx = 1;
	return 3;
}

static int unpack_can_0x105_TempFrontR(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 3)
		return -1;
	/* temp_mot_pot_FR: start-bit 0, length 10, endianess intel, scaling 1, offset 0 */
	x = i & 0x3ff;
	o->can_0x105_TempFrontR.temp_mot_pot_FR = x;
	/* temp_mot_pre_FR: start-bit 10, length 10, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x3ff;
	o->can_0x105_TempFrontR.temp_mot_pre_FR = x;
	o->can_0x105_TempFrontR_rx = 1;
	o->can_0x105_TempFrontR_time_stamp_rx = time_stamp;
	return 3;
}

int decode_can_0x105_temp_mot_pot_FR(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x105_TempFrontR.temp_mot_pot_FR);
	*out = rval;
	return 0;
}

int encode_can_0x105_temp_mot_pot_FR(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x105_TempFrontR.temp_mot_pot_FR = in;
	return 0;
}

int decode_can_0x105_temp_mot_pre_FR(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x105_TempFrontR.temp_mot_pre_FR);
	*out = rval;
	return 0;
}

int encode_can_0x105_temp_mot_pre_FR(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x105_TempFrontR.temp_mot_pre_FR = in;
	return 0;
}

int print_can_0x105_TempFrontR(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "temp_mot_pot_FR = (wire: %.0f)\n", (double)(o->can_0x105_TempFrontR.temp_mot_pot_FR)));
	r = print_helper(r, fprintf(output, "temp_mot_pre_FR = (wire: %.0f)\n", (double)(o->can_0x105_TempFrontR.temp_mot_pre_FR)));
	return r;
}

static int pack_can_0x120_InvVolt(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* car_voltage: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x120_InvVolt.car_voltage)) & 0xffff;
	i |= x;
	*data = (i);
	o->can_0x120_InvVolt_tx = 1;
	return 2;
}

static int unpack_can_0x120_InvVolt(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* car_voltage: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x120_InvVolt.car_voltage = x;
	o->can_0x120_InvVolt_rx = 1;
	o->can_0x120_InvVolt_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x120_car_voltage(const can_obj_can2_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x120_InvVolt.car_voltage);
	if (rval <= 600) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16_t)0;
		return -1;
	}
}

int encode_can_0x120_car_voltage(can_obj_can2_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x120_InvVolt.car_voltage = 0;
	if (in > 600)
		return -1;
	o->can_0x120_InvVolt.car_voltage = in;
	return 0;
}

int print_can_0x120_InvVolt(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "car_voltage = (wire: %.0f)\n", (double)(o->can_0x120_InvVolt.car_voltage)));
	return r;
}

static int pack_can_0x130_Pcu(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* fan_speed: start-bit 1, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.fan_speed)) & 0x7f;
	x <<= 1; 
	i |= x;
	/* pump_speed: start-bit 9, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.pump_speed)) & 0x7f;
	x <<= 9; 
	i |= x;
	/* fan_enable: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.fan_enable)) & 0x1;
	i |= x;
	/* pump_enable: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x130_Pcu.pump_enable)) & 0x1;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x130_Pcu_tx = 1;
	return 2;
}

static int unpack_can_0x130_Pcu(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 2)
		return -1;
	/* fan_speed: start-bit 1, length 7, endianess intel, scaling 1, offset 0 */
	x = (i >> 1) & 0x7f;
	o->can_0x130_Pcu.fan_speed = x;
	/* pump_speed: start-bit 9, length 7, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x7f;
	o->can_0x130_Pcu.pump_speed = x;
	/* fan_enable: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x130_Pcu.fan_enable = x;
	/* pump_enable: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->can_0x130_Pcu.pump_enable = x;
	o->can_0x130_Pcu_rx = 1;
	o->can_0x130_Pcu_time_stamp_rx = time_stamp;
	return 2;
}

int decode_can_0x130_fan_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.fan_speed);
	*out = rval;
	return 0;
}

int encode_can_0x130_fan_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.fan_speed = in;
	return 0;
}

int decode_can_0x130_pump_speed(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.pump_speed);
	*out = rval;
	return 0;
}

int encode_can_0x130_pump_speed(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.pump_speed = in;
	return 0;
}

int decode_can_0x130_fan_enable(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.fan_enable);
	*out = rval;
	return 0;
}

int encode_can_0x130_fan_enable(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.fan_enable = in;
	return 0;
}

int decode_can_0x130_pump_enable(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x130_Pcu.pump_enable);
	*out = rval;
	return 0;
}

int encode_can_0x130_pump_enable(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x130_Pcu.pump_enable = in;
	return 0;
}

int print_can_0x130_Pcu(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "fan_speed = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.fan_speed)));
	r = print_helper(r, fprintf(output, "pump_speed = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.pump_speed)));
	r = print_helper(r, fprintf(output, "fan_enable = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.fan_enable)));
	r = print_helper(r, fprintf(output, "pump_enable = (wire: %.0f)\n", (double)(o->can_0x130_Pcu.pump_enable)));
	return r;
}

static int pack_can_0x131_Calib(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x131_Calib.position)) & 0xff;
	i |= x;
	switch (o->can_0x131_Calib.position) {
	default:
		return -1;
	}
	*data = (i);
	o->can_0x131_Calib_tx = 1;
	return 1;
}

static int unpack_can_0x131_Calib(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x131_Calib.position = x;
	switch (o->can_0x131_Calib.position) {
	default:
		return -1;
	}
	o->can_0x131_Calib_rx = 1;
	o->can_0x131_Calib_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x131_position(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x131_Calib.position);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x131_position(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x131_Calib.position = 0;
	if (in > 1)
		return -1;
	o->can_0x131_Calib.position = in;
	return 0;
}

int print_can_0x131_Calib(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "position = (wire: %.0f)\n", (double)(o->can_0x131_Calib.position)));
	return r;
}

static int pack_can_0x132_CalibAck(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x132_CalibAck.position)) & 0xff;
	i |= x;
	switch (o->can_0x132_CalibAck.position) {
	default:
		return -1;
	}
	*data = (i);
	o->can_0x132_CalibAck_tx = 1;
	return 1;
}

static int unpack_can_0x132_CalibAck(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 1)
		return -1;
	/* position: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x132_CalibAck.position = x;
	switch (o->can_0x132_CalibAck.position) {
	default:
		return -1;
	}
	o->can_0x132_CalibAck_rx = 1;
	o->can_0x132_CalibAck_time_stamp_rx = time_stamp;
	return 1;
}

int decode_can_0x132_position(const can_obj_can2_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x132_CalibAck.position);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x132_position(can_obj_can2_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x132_CalibAck.position = 0;
	if (in > 1)
		return -1;
	o->can_0x132_CalibAck.position = in;
	return 0;
}

int print_can_0x132_CalibAck(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "position = (wire: %.0f)\n", (double)(o->can_0x132_CalibAck.position)));
	return r;
}

static int pack_can_0x3c2_Lem(can_obj_can2_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* current: start-bit 7, length 32, endianess motorola, scaling 1, offset -2.14748e+09 */
	x = ((uint32_t)(o->can_0x3c2_Lem.current)) & 0xffffffff;
	x <<= 32; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x3c2_Lem_tx = 1;
	return 8;
}

static int unpack_can_0x3c2_Lem(can_obj_can2_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* current: start-bit 7, length 32, endianess motorola, scaling 1, offset -2.14748e+09 */
	x = (m >> 32) & 0xffffffff;
	o->can_0x3c2_Lem.current = x;
	o->can_0x3c2_Lem_rx = 1;
	o->can_0x3c2_Lem_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x3c2_current(const can_obj_can2_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x3c2_Lem.current);
	rval += -2.14748e+09;
	*out = rval;
	return 0;
}

int encode_can_0x3c2_current(can_obj_can2_h_t *o, double in) {
	assert(o);
	in += 2.14748e+09;
	o->can_0x3c2_Lem.current = in;
	return 0;
}

int print_can_0x3c2_Lem(const can_obj_can2_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x3c2_Lem.current)));
	return r;
}

int unpack_message_can2(can_obj_can2_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x052: return unpack_can_0x052_Paddle(o, data, dlc, time_stamp);
	case 0x053: return unpack_can_0x053_Driver(o, data, dlc, time_stamp);
	case 0x054: return unpack_can_0x054_BmsLv1(o, data, dlc, time_stamp);
	case 0x055: return unpack_can_0x055_BmsLv2(o, data, dlc, time_stamp);
	case 0x057: return unpack_can_0x057_BmsHv1(o, data, dlc, time_stamp);
	case 0x058: return unpack_can_0x058_BmsHv2(o, data, dlc, time_stamp);
	case 0x060: return unpack_can_0x060_Imu1(o, data, dlc, time_stamp);
	case 0x061: return unpack_can_0x061_Imu2(o, data, dlc, time_stamp);
	case 0x062: return unpack_can_0x062_Imu3(o, data, dlc, time_stamp);
	case 0x063: return unpack_can_0x063_IMUCalib(o, data, dlc, time_stamp);
	case 0x064: return unpack_can_0x064_Map(o, data, dlc, time_stamp);
	case 0x065: return unpack_can_0x065_CarStatus(o, data, dlc, time_stamp);
	case 0x066: return unpack_can_0x066_CarSettings(o, data, dlc, time_stamp);
	case 0x070: return unpack_can_0x070_LapStart(o, data, dlc, time_stamp);
	case 0x100: return unpack_can_0x100_Temp1(o, data, dlc, time_stamp);
	case 0x101: return unpack_can_0x101_Temp2(o, data, dlc, time_stamp);
	case 0x102: return unpack_can_0x102_SuspRear(o, data, dlc, time_stamp);
	case 0x103: return unpack_can_0x103_RESERVED2(o, data, dlc, time_stamp);
	case 0x104: return unpack_can_0x104_SuspFront(o, data, dlc, time_stamp);
	case 0x105: return unpack_can_0x105_TempFrontR(o, data, dlc, time_stamp);
	case 0x120: return unpack_can_0x120_InvVolt(o, data, dlc, time_stamp);
	case 0x130: return unpack_can_0x130_Pcu(o, data, dlc, time_stamp);
	case 0x131: return unpack_can_0x131_Calib(o, data, dlc, time_stamp);
	case 0x132: return unpack_can_0x132_CalibAck(o, data, dlc, time_stamp);
	case 0x3c2: return unpack_can_0x3c2_Lem(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message_can2(can_obj_can2_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x052: return pack_can_0x052_Paddle(o, data);
	case 0x053: return pack_can_0x053_Driver(o, data);
	case 0x054: return pack_can_0x054_BmsLv1(o, data);
	case 0x055: return pack_can_0x055_BmsLv2(o, data);
	case 0x057: return pack_can_0x057_BmsHv1(o, data);
	case 0x058: return pack_can_0x058_BmsHv2(o, data);
	case 0x060: return pack_can_0x060_Imu1(o, data);
	case 0x061: return pack_can_0x061_Imu2(o, data);
	case 0x062: return pack_can_0x062_Imu3(o, data);
	case 0x063: return pack_can_0x063_IMUCalib(o, data);
	case 0x064: return pack_can_0x064_Map(o, data);
	case 0x065: return pack_can_0x065_CarStatus(o, data);
	case 0x066: return pack_can_0x066_CarSettings(o, data);
	case 0x070: return pack_can_0x070_LapStart(o, data);
	case 0x100: return pack_can_0x100_Temp1(o, data);
	case 0x101: return pack_can_0x101_Temp2(o, data);
	case 0x102: return pack_can_0x102_SuspRear(o, data);
	case 0x103: return pack_can_0x103_RESERVED2(o, data);
	case 0x104: return pack_can_0x104_SuspFront(o, data);
	case 0x105: return pack_can_0x105_TempFrontR(o, data);
	case 0x120: return pack_can_0x120_InvVolt(o, data);
	case 0x130: return pack_can_0x130_Pcu(o, data);
	case 0x131: return pack_can_0x131_Calib(o, data);
	case 0x132: return pack_can_0x132_CalibAck(o, data);
	case 0x3c2: return pack_can_0x3c2_Lem(o, data);
	default: break; 
	}
	return -1; 
}

int print_message_can2(const can_obj_can2_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x052: return print_can_0x052_Paddle(o, output);
	case 0x053: return print_can_0x053_Driver(o, output);
	case 0x054: return print_can_0x054_BmsLv1(o, output);
	case 0x055: return print_can_0x055_BmsLv2(o, output);
	case 0x057: return print_can_0x057_BmsHv1(o, output);
	case 0x058: return print_can_0x058_BmsHv2(o, output);
	case 0x060: return print_can_0x060_Imu1(o, output);
	case 0x061: return print_can_0x061_Imu2(o, output);
	case 0x062: return print_can_0x062_Imu3(o, output);
	case 0x063: return print_can_0x063_IMUCalib(o, output);
	case 0x064: return print_can_0x064_Map(o, output);
	case 0x065: return print_can_0x065_CarStatus(o, output);
	case 0x066: return print_can_0x066_CarSettings(o, output);
	case 0x070: return print_can_0x070_LapStart(o, output);
	case 0x100: return print_can_0x100_Temp1(o, output);
	case 0x101: return print_can_0x101_Temp2(o, output);
	case 0x102: return print_can_0x102_SuspRear(o, output);
	case 0x103: return print_can_0x103_RESERVED2(o, output);
	case 0x104: return print_can_0x104_SuspFront(o, output);
	case 0x105: return print_can_0x105_TempFrontR(o, output);
	case 0x120: return print_can_0x120_InvVolt(o, output);
	case 0x130: return print_can_0x130_Pcu(o, output);
	case 0x131: return print_can_0x131_Calib(o, output);
	case 0x132: return print_can_0x132_CalibAck(o, output);
	case 0x3c2: return print_can_0x3c2_Lem(o, output);
	default: break; 
	}
	return -1; 
}

