/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "can3.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x1f4_DV_driving_dynamics_1(can_obj_can3_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Speed_actual: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Speed_actual)) & 0xff;
	i |= x;
	/* Speed_target: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Speed_target)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Steering_angle_actual: start-bit 16, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual)) & 0xff;
	x <<= 16; 
	i |= x;
	/* Steering_angle_target: start-bit 24, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target)) & 0xff;
	x <<= 24; 
	i |= x;
	/* Brake_hydr_actual: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual)) & 0xff;
	x <<= 32; 
	i |= x;
	/* Brake_hydr_target: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Motor_moment_actual: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_actual)) & 0xff;
	x <<= 48; 
	i |= x;
	/* Motor_moment_target: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_target)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x1f4_DV_driving_dynamics_1_tx = 1;
	return 8;
}

static int unpack_can_0x1f4_DV_driving_dynamics_1(can_obj_can3_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Speed_actual: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Speed_actual = x;
	/* Speed_target: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Speed_target = x;
	/* Steering_angle_actual: start-bit 16, length 8, endianess intel, scaling 0.5, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual = x;
	/* Steering_angle_target: start-bit 24, length 8, endianess intel, scaling 0.5, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target = x;
	/* Brake_hydr_actual: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual = x;
	/* Brake_hydr_target: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target = x;
	/* Motor_moment_actual: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_actual = x;
	/* Motor_moment_target: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_target = x;
	o->can_0x1f4_DV_driving_dynamics_1_rx = 1;
	o->can_0x1f4_DV_driving_dynamics_1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x1f4_Speed_actual(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Speed_actual);
	*out = rval;
	return 0;
}

int encode_can_0x1f4_Speed_actual(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Speed_actual = in;
	return 0;
}

int decode_can_0x1f4_Speed_target(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Speed_target);
	*out = rval;
	return 0;
}

int encode_can_0x1f4_Speed_target(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Speed_target = in;
	return 0;
}

int decode_can_0x1f4_Steering_angle_actual(const can_obj_can3_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual);
	rval *= 0.5;
	if (rval >= -127) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x1f4_Steering_angle_actual(can_obj_can3_h_t *o, double in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual = 0;
	if (in < -127)
		return -1;
	in *= 2;
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual = in;
	return 0;
}

int decode_can_0x1f4_Steering_angle_target(const can_obj_can3_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target);
	rval *= 0.5;
	if (rval >= -127) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x1f4_Steering_angle_target(can_obj_can3_h_t *o, double in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target = 0;
	if (in < -127)
		return -1;
	in *= 2;
	o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target = in;
	return 0;
}

int decode_can_0x1f4_Brake_hydr_actual(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x1f4_Brake_hydr_actual(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual = 0;
	if (in > 100)
		return -1;
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual = in;
	return 0;
}

int decode_can_0x1f4_Brake_hydr_target(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x1f4_Brake_hydr_target(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target = 0;
	if (in > 100)
		return -1;
	o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target = in;
	return 0;
}

int decode_can_0x1f4_Motor_moment_actual(const can_obj_can3_h_t *o, int8_t *out) {
	assert(o);
	assert(out);
	int8_t rval = (int8_t)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_actual);
	*out = rval;
	return 0;
}

int encode_can_0x1f4_Motor_moment_actual(can_obj_can3_h_t *o, int8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_actual = in;
	return 0;
}

int decode_can_0x1f4_Motor_moment_target(const can_obj_can3_h_t *o, int8_t *out) {
	assert(o);
	assert(out);
	int8_t rval = (int8_t)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_target);
	*out = rval;
	return 0;
}

int encode_can_0x1f4_Motor_moment_target(can_obj_can3_h_t *o, int8_t in) {
	assert(o);
	o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_target = in;
	return 0;
}

int print_can_0x1f4_DV_driving_dynamics_1(const can_obj_can3_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Speed_actual = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Speed_actual)));
	r = print_helper(r, fprintf(output, "Speed_target = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Speed_target)));
	r = print_helper(r, fprintf(output, "Steering_angle_actual = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_actual)));
	r = print_helper(r, fprintf(output, "Steering_angle_target = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Steering_angle_target)));
	r = print_helper(r, fprintf(output, "Brake_hydr_actual = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_actual)));
	r = print_helper(r, fprintf(output, "Brake_hydr_target = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Brake_hydr_target)));
	r = print_helper(r, fprintf(output, "Motor_moment_actual = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_actual)));
	r = print_helper(r, fprintf(output, "Motor_moment_target = (wire: %.0f)\n", (double)(o->can_0x1f4_DV_driving_dynamics_1.Motor_moment_target)));
	return r;
}

static int pack_can_0x1f5_DV_driving_dynamics_2(can_obj_can3_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Acceleration_longitudinal: start-bit 0, length 16, endianess intel, scaling 0.0005, offset 0 */
	x = ((uint16_t)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal)) & 0xffff;
	i |= x;
	/* Acceleration_lateral: start-bit 16, length 16, endianess intel, scaling 0.0005, offset 0 */
	x = ((uint16_t)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* Yaw_rate: start-bit 32, length 16, endianess intel, scaling 0.0078125, offset 0 */
	x = ((uint16_t)(o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x1f5_DV_driving_dynamics_2_tx = 1;
	return 6;
}

static int unpack_can_0x1f5_DV_driving_dynamics_2(can_obj_can3_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 6)
		return -1;
	/* Acceleration_longitudinal: start-bit 0, length 16, endianess intel, scaling 0.0005, offset 0 */
	x = i & 0xffff;
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal = x;
	/* Acceleration_lateral: start-bit 16, length 16, endianess intel, scaling 0.0005, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral = x;
	/* Yaw_rate: start-bit 32, length 16, endianess intel, scaling 0.0078125, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate = x;
	o->can_0x1f5_DV_driving_dynamics_2_rx = 1;
	o->can_0x1f5_DV_driving_dynamics_2_time_stamp_rx = time_stamp;
	return 6;
}

int decode_can_0x1f5_Acceleration_longitudinal(const can_obj_can3_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal);
	rval *= 0.0005;
	if ((rval >= -16.384) && (rval <= 16.384)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x1f5_Acceleration_longitudinal(can_obj_can3_h_t *o, double in) {
	assert(o);
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal = 0;
	if (in < -16.384)
		return -1;
	if (in > 16.384)
		return -1;
	in *= 2000;
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal = in;
	return 0;
}

int decode_can_0x1f5_Acceleration_lateral(const can_obj_can3_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral);
	rval *= 0.0005;
	if ((rval >= -16.384) && (rval <= 16.384)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x1f5_Acceleration_lateral(can_obj_can3_h_t *o, double in) {
	assert(o);
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral = 0;
	if (in < -16.384)
		return -1;
	if (in > 16.384)
		return -1;
	in *= 2000;
	o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral = in;
	return 0;
}

int decode_can_0x1f5_Yaw_rate(const can_obj_can3_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate);
	rval *= 0.0078125;
	if ((rval >= -256) && (rval <= 256)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x1f5_Yaw_rate(can_obj_can3_h_t *o, double in) {
	assert(o);
	o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate = 0;
	if (in < -256)
		return -1;
	if (in > 256)
		return -1;
	in *= 128;
	o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate = in;
	return 0;
}

int print_can_0x1f5_DV_driving_dynamics_2(const can_obj_can3_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Acceleration_longitudinal = (wire: %.0f)\n", (double)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_longitudinal)));
	r = print_helper(r, fprintf(output, "Acceleration_lateral = (wire: %.0f)\n", (double)(o->can_0x1f5_DV_driving_dynamics_2.Acceleration_lateral)));
	r = print_helper(r, fprintf(output, "Yaw_rate = (wire: %.0f)\n", (double)(o->can_0x1f5_DV_driving_dynamics_2.Yaw_rate)));
	return r;
}

static int pack_can_0x1f6_DV_system_status(can_obj_can3_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Cones_count_all: start-bit 23, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x1f6_DV_system_status.Cones_count_all)) & 0xffff;
	x <<= 23; 
	i |= x;
	/* Cones_count_actual: start-bit 15, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.Cones_count_actual)) & 0xff;
	x <<= 15; 
	i |= x;
	/* Lap_counter: start-bit 11, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.Lap_counter)) & 0xf;
	x <<= 11; 
	i |= x;
	/* AS_state: start-bit 0, length 3, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.AS_state)) & 0x7;
	i |= x;
	/* AMI_state: start-bit 5, length 3, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.AMI_state)) & 0x7;
	x <<= 5; 
	i |= x;
	/* EBS_state: start-bit 3, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.EBS_state)) & 0x3;
	x <<= 3; 
	i |= x;
	/* Service_brake_state: start-bit 9, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.Service_brake_state)) & 0x3;
	x <<= 9; 
	i |= x;
	/* Steering_state: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f6_DV_system_status.Steering_state)) & 0x1;
	x <<= 8; 
	i |= x;
	*data = (i);
	o->can_0x1f6_DV_system_status_tx = 1;
	return 5;
}

static int unpack_can_0x1f6_DV_system_status(can_obj_can3_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 5)
		return -1;
	/* Cones_count_all: start-bit 23, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 23) & 0xffff;
	o->can_0x1f6_DV_system_status.Cones_count_all = x;
	/* Cones_count_actual: start-bit 15, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 15) & 0xff;
	o->can_0x1f6_DV_system_status.Cones_count_actual = x;
	/* Lap_counter: start-bit 11, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 11) & 0xf;
	o->can_0x1f6_DV_system_status.Lap_counter = x;
	/* AS_state: start-bit 0, length 3, endianess intel, scaling 1, offset 0 */
	x = i & 0x7;
	o->can_0x1f6_DV_system_status.AS_state = x;
	/* AMI_state: start-bit 5, length 3, endianess intel, scaling 1, offset 0 */
	x = (i >> 5) & 0x7;
	o->can_0x1f6_DV_system_status.AMI_state = x;
	/* EBS_state: start-bit 3, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 3) & 0x3;
	o->can_0x1f6_DV_system_status.EBS_state = x;
	/* Service_brake_state: start-bit 9, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x3;
	o->can_0x1f6_DV_system_status.Service_brake_state = x;
	/* Steering_state: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->can_0x1f6_DV_system_status.Steering_state = x;
	o->can_0x1f6_DV_system_status_rx = 1;
	o->can_0x1f6_DV_system_status_time_stamp_rx = time_stamp;
	return 5;
}

int decode_can_0x1f6_Cones_count_all(const can_obj_can3_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x1f6_DV_system_status.Cones_count_all);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_Cones_count_all(can_obj_can3_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.Cones_count_all = in;
	return 0;
}

int decode_can_0x1f6_Cones_count_actual(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.Cones_count_actual);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_Cones_count_actual(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.Cones_count_actual = in;
	return 0;
}

int decode_can_0x1f6_Lap_counter(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.Lap_counter);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_Lap_counter(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.Lap_counter = in;
	return 0;
}

int decode_can_0x1f6_AS_state(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.AS_state);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_AS_state(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.AS_state = in;
	return 0;
}

int decode_can_0x1f6_AMI_state(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.AMI_state);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_AMI_state(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.AMI_state = in;
	return 0;
}

int decode_can_0x1f6_EBS_state(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.EBS_state);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_EBS_state(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.EBS_state = in;
	return 0;
}

int decode_can_0x1f6_Service_brake_state(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.Service_brake_state);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_Service_brake_state(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.Service_brake_state = in;
	return 0;
}

int decode_can_0x1f6_Steering_state(const can_obj_can3_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f6_DV_system_status.Steering_state);
	*out = rval;
	return 0;
}

int encode_can_0x1f6_Steering_state(can_obj_can3_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f6_DV_system_status.Steering_state = in;
	return 0;
}

int print_can_0x1f6_DV_system_status(const can_obj_can3_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Cones_count_all = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.Cones_count_all)));
	r = print_helper(r, fprintf(output, "Cones_count_actual = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.Cones_count_actual)));
	r = print_helper(r, fprintf(output, "Lap_counter = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.Lap_counter)));
	r = print_helper(r, fprintf(output, "AS_state = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.AS_state)));
	r = print_helper(r, fprintf(output, "AMI_state = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.AMI_state)));
	r = print_helper(r, fprintf(output, "EBS_state = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.EBS_state)));
	r = print_helper(r, fprintf(output, "Service_brake_state = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.Service_brake_state)));
	r = print_helper(r, fprintf(output, "Steering_state = (wire: %.0f)\n", (double)(o->can_0x1f6_DV_system_status.Steering_state)));
	return r;
}

int unpack_message_can3(can_obj_can3_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x1f4: return unpack_can_0x1f4_DV_driving_dynamics_1(o, data, dlc, time_stamp);
	case 0x1f5: return unpack_can_0x1f5_DV_driving_dynamics_2(o, data, dlc, time_stamp);
	case 0x1f6: return unpack_can_0x1f6_DV_system_status(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message_can3(can_obj_can3_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x1f4: return pack_can_0x1f4_DV_driving_dynamics_1(o, data);
	case 0x1f5: return pack_can_0x1f5_DV_driving_dynamics_2(o, data);
	case 0x1f6: return pack_can_0x1f6_DV_system_status(o, data);
	default: break; 
	}
	return -1; 
}

int print_message_can3(const can_obj_can3_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x1f4: return print_can_0x1f4_DV_driving_dynamics_1(o, output);
	case 0x1f5: return print_can_0x1f5_DV_driving_dynamics_2(o, output);
	case 0x1f6: return print_can_0x1f6_DV_system_status(o, output);
	default: break; 
	}
	return -1; 
}

