################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
ELF_SRCS := 
LSL_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Configurations/Debug \
Configurations \
. \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC37A/Tricore \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/iLLD/TC37A/Tricore/Asclin/Asc \
Libraries/iLLD/TC37A/Tricore/Asclin/Std \
Libraries/iLLD/TC37A/Tricore/Can/Can \
Libraries/iLLD/TC37A/Tricore/Can/Std \
Libraries/iLLD/TC37A/Tricore/Cpu/Irq \
Libraries/iLLD/TC37A/Tricore/Cpu/Std \
Libraries/iLLD/TC37A/Tricore/Cpu/Trap \
Libraries/iLLD/TC37A/Tricore/Gtm/Std \
Libraries/iLLD/TC37A/Tricore/Mtu/Std \
Libraries/iLLD/TC37A/Tricore/Pms/Std \
Libraries/iLLD/TC37A/Tricore/Port/Std \
Libraries/iLLD/TC37A/Tricore/Scu/Std \
Libraries/iLLD/TC37A/Tricore/Src/Std \
Libraries/iLLD/TC37A/Tricore/Stm/Std \
Libraries/iLLD/TC37A/Tricore/_Impl \
Libraries/iLLD/TC37A/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC37A/Tricore/_PinMap \
driver_imp/can \
driver_imp/ethernet \
driver_imp/gpio \
driver_imp/serial \
driver_imp/timer \
src/cores/core_0 \
src/cores/core_0/feature/driver_input \
src/cores/core_0/feature/engines/amk \
src/cores/core_0/feature \
src/cores/core_0/feature/giei \
src/cores/core_0/feature/giei/giei_components/hv \
src/cores/core_0/feature/giei/giei_components/power_control \
src/cores/core_0/feature/giei/giei_components/regen_alg \
src/cores/core_0/feature/giei/giei_components/speed_alg \
src/cores/core_0/feature/giei/giei_components/torque_vec_alg \
src/cores/core_0/feature/maps \
src/cores/core_0/feature/math_saturated \
src/cores/core_1 \
src/cores/core_1/feature/batteries \
src/cores/core_1/feature/batteries/bms \
src/cores/core_1/feature/cooling \
src/cores/core_1/feature/core_1_driver_input \
src/cores/core_1/feature/core_1_imu \
src/cores/core_1/feature \
src/cores/core_1/feature/log/external_log_variables \
src/cores/core_1/feature/log \
src/cores/core_1/feature/log/sd \
src/cores/core_1/feature/log/telemetry/json_builder \
src/cores/core_1/feature/log/telemetry \
src/cores/core_1/feature/suspensions \
src/cores/core_2 \
src/cores/core_2/feature/DV \
src/cores/core_2/feature/DV/ebs \
src/cores/core_2/feature/DV/res \
src/cores/core_2/feature/DV/steering_wheel_alg \
src/cores/core_2/feature \
src/cores/core_utility/alive_blink \
src/cores/core_utility/as_node \
src/cores/core_utility/core_status \
src/cores/core_utility/driver_input_reader \
src/cores/core_utility/emergency_module \
src/cores/core_utility/imu \
src/cores/core_utility/mission_reader/mission_locker \
src/cores/core_utility/mission_reader \
src/cores/core_utility/rtd_assi_sound \
src/cores/core_utility/running_status \
src/lib/Cmemory \
src/lib/DPS \
src/lib/DPS/lib/c_vector \
src/lib/TV \
src/lib/board_dbc/dbc/out_lib/can1 \
src/lib/board_dbc/dbc/out_lib/can2 \
src/lib/board_dbc/dbc/out_lib/can3 \
src/lib/board_dbc/dbc/out_lib/cansbg \
src/lib/rigen_fun_simulink22_ert_rtw \

